### ISSUE TITLE
Excessive amount of golems spawning ( MC 1.12.2 )

### ISSUE THREAD

**Issue by Kasia1403** [MinecraftModDevelopmentMods/Extra-Golems#100]
Please fix it !
![2022-04-03_18 49 16](https://user-images.githubusercontent.com/54236098/161438818-d0741878-dfbc-4ad7-b294-6d8200aea24c.png)

**Comment by skyjay1** [comment]
1.12 version is no longer supported. Sorry.

**Comment by Kasia1403** [comment]
I think I fixed it. I changed spawnrate.
