### ISSUE TITLE
[Suggestion] Add a follow option for golems and an in-game book describing differences between golems

### ISSUE THREAD

**Issue by afghan2007** [MinecraftModDevelopmentMods/Extra-Golems#3]
Golems are cool and the variety is wonderful. but the default golem just roams an area and  attacks nearby mobs.  I was wondering if it would be possible to add a follow option similar to that of say a dog following his master, maybe even teleport to the master if he gets too far away while on follow.

Also, a side idea.  Would it be possible to get an in-game book describing the difference between each golem.  It would be more convenient then constantly checking curse.com...I have a horrible memory.

Thank either way.

**Comment by skyjay1** [comment]
Added beta-version of in-game info book (WIP). Follow option is under consideration.

**Comment by skyjay1** [comment]
In-Game information book has been added. A follow option for golems will not be added at this time. Thank you for the ideas!
