### ISSUE TITLE
[Suggestion/Request] Allow for EG Golem too be Thaumcraft Scannable for Golem research

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/Extra-Golems#9]
self explanatory, as seen in https://github.com/Azanor/thaumcraft-beta/issues/1356

**Comment by drakray** [comment]
Would be very nice, as vanilla Iron Golem can be expensive just to unlock a main portion of TC, when a Wood Golem could do.
Could be a config option, if people think it's cheaty, though if you add Extra Golem with Thaumcraft, one might want them to work this way lol

**Comment by drakray** [comment]
I asked [ModTweaker](https://github.com/jaredlll08/ModTweaker/issues/674), but they won't add something that can't be removed, understandably given the nature of CT/MT, and that EG is one of, if not the, only mod that add Golem ;) :D

**Comment by skyjay1** [comment]
Thaumcraft appears to not be available for 1.18, 1.19, or 1.20
